AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 bastion host in public subnet

Parameters:
  VpcId:
    Type: String
    Description: ID of the VPC
  PublicSubnetId:
    Type: String
    Description: ID of the public subnet
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair

Resources:
  BastionSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for bastion host (SSH access)
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags: [{ Key: Name, Value: Bastion-SG }]

  BastionEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c1ac8a41498c1a9c
      InstanceType: t3.micro
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds: [!Ref BastionSG]
      KeyName: !Ref KeyName
      Tags: [{ Key: Name, Value: Bastion-Host }]
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y awscli kubectl
          echo "Bastion host setup complete" > /tmp/setup.log

Outputs:
  BastionPublicIp:
    Value: !GetAtt BastionEC2.PublicIp
    Export:
      Name: Bastion-Public-IP