AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack to orchestrate VPC and EC2 stacks

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair

Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloud-formation-yaml-files-01.s3.eu-north-1.amazonaws.com/vpc-stack.yaml
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://cloud-formation-yaml-files-01.s3.eu-north-1.amazonaws.com/ec2-stack.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        KeyName: !Ref KeyName
